[package]
name = "emu6502"
version = "0.1.0"
authors = ["Gustavo Moitinho Trindade <gustavo.moitinho@outlook.com>"]
edition = "2018"

[dependencies]
regex = "1.3"
lazy_static = "1.4"
log = "0.4"
env_logger = "0.7"
